create table erp_siparisdetay
(
 id int NOT NULL,
 userId int NOT NULL,
 siparisId int NOT NULL,
 evrakNo nvarchar(20),
 siparisNo nvarchar(20),
 stokId nvarchar(20),
 stokBirimId int NOT NULL,
 stokSenkronizasyon nvarchar(50) NOT NULL,
 miktar decimal(10,0) NOT NULL,
 cikisMiktari decimal(10,0) NOT NULL,
 kalanMiktar decimal(10,0) NOT NULL,
 irsMiktar decimal(10,0) NOT NULL,
 fatMiktar decimal(10,0) NOT NULL,
 birimFiyatTl decimal(10,3) NOT NULL,
 birimFiyatdov decimal(10,3) NOT NULL,
 iskontoTl decimal(10,3) NOT NULL,
 kdv int NOT NULL,
 kdvTutari decimal(10,3) NOT NULL,
 iskontoluTutar decimal(10,3) NOT NULL,
 iskontoOrani decimal(10,3) NOT NULL,
 iskontoOrani2 decimal(10,3) NOT NULL,
 tutar decimal(18,3) NOT NULL,
 netTutarDov decimal(18,3) NOT NULL,
 dovizKuru decimal(18,3) NOT NULL,
 netTutar decimal(10,3) NOT NULL,
 aciklama nvarchar(250) NOT NULL,
 cariId int NOT NULL,
 aktiviteKodu nvarchar(50) NOT NULL,
 senkronizasyon nvarchar(50) NOT NULL,
 sepet tinyint NOT NULL,
 subeId int NOT NULL,
 firmId int NOT NULL,
 kaydeden int NOT NULL,
 kayitTarihi datetime NOT NULL,
 guncelleyen int NOT NULL,
 guncellemeTarihi datetime NOT NULL,
 kargoNo nvarchar(50) NOT NULL,
 irsaliyeNo nvarchar(20) NOT NULL,
 faturaNo nvarchar(20) NOT NULL,
 teslimBelgeNo nvarchar(50) NOT NULL,
 teslimAciklama nvarchar(250) NOT NULL
)         