create table erp_sipairshareket
(
 id int NOT NULL,
 siparisId int NOT NULL,
 siparisKalemId int NOT NULL,
 belgeNo nvarchar(20) NOT NULL,
 tipi tinyint NOT NULL,
 cariId int NOT NULL,
 aciklama nvarchar(250) NOT NULL,
 firmId int NOT NULL,
 subeId int NOT NULL,
 stokId nvarchar(50) NOT NULL,
 siparisNo nvarchar(20) NOT NULL,
 miktar decimal(10,2) NOT NULL,
 cikisMiktari decimal(10,2) NOT NULL,
 kalanMiktar decimal(10,2) NOT NULL,
 kargofirmasi int NOT NULL,
 gcKod tinyint NOT NULL,
 faturaNo nvarchar(20) NOT NULL,
 fatTarihi date NOT NULL,
 irsaliyeNo nvarchar(20) NOT NULL,
 irsTarihi date NOT NULL,
 status tinyint NOT NULL,
 kaydeden int NOT NULL,
 kayitZamani datetime NOT NULL,
 fisNo nvarchar(11) NOT NULL
) 