create table erp_stok
(
 id int NOT NULL,
 firmId int NOT NULL,
 kod nvarchar(50) NOT NULL,
 parentKod nvarchar(50) NOT NULL,
 kartTipi int NOT NULL,
 isim nvarchar(200) NOT NULL,
 isim2 nvarchar(250) NOT NULL,
 senkronizasyond nvarchar(50) NOT NULL,
 kdv int NOT NULL,
 aktif tinyint NOT NULL,
 birim int NOT NULL,
 ozelkod nvarchar(30) NOT NULL,
 ozelkod2 nvarchar(30) NOT NULL,
 satisFiyati decimal(10,2) NOT NULL,
 satisFiyati2 decimal(10,2) NOT NULL,
 satisFiyati3 decimal(10,2) NOT NULL,
 guncelleyen int NOT NULL,
 guncellemeZamani datetime NOT NULL,
 satistipiDov tinyint NOT NULL,
 en decimal(10,2) NOT NULL,
 boy decimal(10,2) NOT NULL,
 yukseklik decimal(10,2) NOT NULL,
 derinlik decimal(10,2) NOT NULL,
 renk int NOT NULL,
 agirlik decimal(10,2) NOT NULL,
 kaydeden int NOT NULL,
 satisfiyati4 decimal(10,2) NOT NULL,
 kayitZamani datetime NOT NULL
) 